name: Laravel

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  laravel-tests:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit
- name: Cache
  uses: actions/cache@v1.1.2
  with:
    # A directory to store and save the cache
    path: 
    # An explicit key for restoring and saving the cache
    key: 
    # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
    restore-keys: # optional
    - name: Setup Go for use with actions
  uses: actions/setup-go@v1.0.0
  with:
    # The Go version to download (if necessary) and use. Example: 1.9.3
    version: # optional, default is 1.10
    - name: Setup Go for use with actions
  uses: actions/setup-go@v1.0.0
  with:
    # The Go version to download (if necessary) and use. Example: 1.9.3
    version: # optional, default is 1.10
    - name: Close Stale Issues
  uses: actions/stale@1.0.0
  with:
    # Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # The message to post on the issue when tagging it. If none provided, will not mark iusses stale.
    stale-issue-message: # optional
    # The message to post on the pr when tagging it. If none provided, will not mark prs stale.
    stale-pr-message: # optional
    # The number of days old an issue can be before marking it stale
    days-before-stale: # optional, default is 60
    # The number of days to wait to close an issue or pr after it being marked stale
    days-before-close: # optional, default is 7
    # The label to apply when an issue is stale
    stale-issue-label: # optional, default is Stale
    # The label to apply when a pr is stale
    stale-pr-label: # optional, default is Stale
    # The maximum number of operations per run, used to control rate limiting
    operations-per-run: # optional, default is 30
    - name: First interaction
  uses: actions/first-interaction@v1.0.0
  with:
    # Token for the repo. Can be passed in using {{ secrets.GITHUB_TOKEN }}
    repo-token: 
    # Comment to post on an individuals first issue
    issue-message: # optional
    # Comment to post on an individuals first pull request
    pr-message: # optional
